name: "Example Company"
url: http://example.com
ga: "UA-XXXXXXXX-Y"
github_hosted: true
show_footer: true
favicon: true
multilingual: false
printable: true
dyslexia_support: true

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "Gemfile.github-pages"
    - "Gemfile.github-pages.lock"
    - "LICENSE.md"
    - "README.md"
    - "WRITERS.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"
    - "s3_website.yml"

sass:
    sass_dir: static/css/
    sourcemap: :auto
    style: :nested
